/**
 * This class is generated by jOOQ
 */
package com.bhargav.sales.quickstart;


import com.bhargav.sales.quickstart.tables.Customer;
import com.bhargav.sales.quickstart.tables.Event;
import com.bhargav.sales.quickstart.tables.Item;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sales extends SchemaImpl {

    private static final long serialVersionUID = -2072459946;

    /**
     * The reference instance of <code>sales</code>
     */
    public static final Sales SALES = new Sales();

    /**
     * The table <code>sales.Customer</code>.
     */
    public final Customer CUSTOMER = com.bhargav.sales.quickstart.tables.Customer.CUSTOMER;

    /**
     * The table <code>sales.Event</code>.
     */
    public final Event EVENT = com.bhargav.sales.quickstart.tables.Event.EVENT;

    /**
     * The table <code>sales.item</code>.
     */
    public final Item ITEM = com.bhargav.sales.quickstart.tables.Item.ITEM;

    /**
     * No further instances allowed
     */
    private Sales() {
        super("sales", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            Event.EVENT,
            Item.ITEM);
    }
}
